### ISSUE TITLE
打开ADB后建议的操作（个人分享）

### ISSUE THREAD

**Issue by jdjingdian** [hackxpeng/hackp5g9#2]
个人认为这个方法随时可能会被热更新修复，xpeng可以在应用层做规避，因此，建议使用 https://github.com/MuntashirAkon/SetEdit

安装后用`adb shell pm grant 包名 权限名` 给SetEdit写系统设置的权限，这样即便上层规避了，你也可以继续使用setEdit修改数据库来打开adb

**Comment by kissggj123** [comment]
![image](https://github.com/hackxpeng/hackp5g9/assets/8959123/bcaa176a-1e02-41b1-808b-5233f129145a)
尝试过了 修改adb_enabled值不管用 还是需要解锁码

**Comment by jdjingdian** [comment]
> ![image](https://user-images.githubusercontent.com/8959123/266794769-bcaa176a-1e02-41b1-808b-5233f129145a.png)
> 尝试过了 修改adb_enabled值不管用 还是需要解锁码

我的意思大概是这样的
1. 先用解锁码获取adb
2. 安装能够设置属性的应用
3. 赋予应用写SETTINGS和SECURE_SETTINGS的权限
4. 修改adb_enabled
5. 修改usb模式

这样子即便之后解锁码失效也能用应用去设置，重新开adb

[sys.xiaopeng.usb.debug]: [false]
[sys.usb.config]: [adb]
[persist.sys.usb.config]: [adb]

getprop看了一下有这些跟usb相关，我怀疑是adb_enabled和usb模式一起设置才能生效

**Comment by kissggj123** [comment]
我昨晚已经试过了 不起作用似乎只能解锁码

**Comment by YIFAN0831** [comment]
输入解锁码后不会自动消失，貌似没有反应

手动删除后输入*#9387*141#*也没有反应

**Comment by dodhunzhu** [comment]
> 输入解锁码后不会自动消失，貌似没有反应
> 
> 手动删除后输入*#9387*141#*也没有反应

G6 4.3.1 和兄弟的情况一毛一样

**Comment by qmm0523** [comment]
跑通了,详细说下具体流程吧:
1.获取到车机adb
2.下载https://github.com/MuntashirAkon/SetEdit 安装到车机
3.adb shell进入命令行,执行以下两条命令:
pm grant  io.github.muntashirakon.setedit android.permission.WRITE_SETTINGS
pm grant  io.github.muntashirakon.setedit android.permission.WRITE_SECURE_SETTINGS
4.进入setedit - global table- xp_usb_mode修改内容即可自由开关有线adb:
usb_host(=adb关闭) usb_device(=adb打开)

BTW, 强烈建议不要打开无线adb, 主流手机在陌生设备连接adb的时，检测到陌生设备(RSA指纹不同)都会弹出提示框要求二次确认，而小鹏tbox目前看来没有任何二次确认流程，只要网络可达即可远程连接adb，安全风险非常大。

**Comment by YIFAN0831** [comment]
大佬，新版本有啥办法不？G9测试版解锁码没用@qmm0523

**Comment by qmm0523** [comment]
> [YIFAN0831](/YIFAN0831)

去售后回滚老版本试一下？

**Comment by jdjingdian** [comment]
可能没什么用了，xpeng已经开始热更新修复了

> > [YIFAN0831](/YIFAN0831)
> 
> 去售后回滚老版本试一下？

**Comment by YIFAN0831** [comment]
你这个建议好@qmm0523 我明天去找售后


@jdjingdian 问题现在G9的正式版本都可以

**Comment by jdjingdian** [comment]
> 你这个建议好@qmm0523 我明天去找售后
> 
> @jdjingdian 问题现在G9的正式版本都可以

那可得快马加鞭，哈哈

**Comment by YIFAN0831** [comment]
![IMG_20230910_224743.jpg](https://github.com/hackxpeng/hackp5g9/assets/144593707/dfb87cea-00ba-4f45-ac1e-44472818318a)



试试看

**Comment by YIFAN0831** [comment]
没戏，刚刚客服说OTA不可逆向，各位大佬还有啥办法不？@jdjingdian @qmm0523

**Comment by kissggj123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Simle** [comment]
> 没戏，刚刚客服说OTA不可逆向，各位大佬还有啥办法不？@jdjingdian @qmm0523 

要求回炉，车机系统恢复出厂设置😄

**Comment by nian-yh** [comment]
G6有跑通的大佬吗

**Comment by huzai9527** [comment]
您好，我是网络安全专业的学生，如您方便，可否提p5,p7的相关so文件，想尝试分析一下，如果可以的话，可以发送到[callmehuzai@gmail.com](mailto:callmehuzai@gmail.com)

**Comment by zhengweiqing** [comment]
pm grant io.github.muntashirakon.setedit android.permission.WRITE_SECURE_SETTINGS
上边这条命令成功了，下边这个出错了。
执行命令后出错了，提示没有权限啊
d55:/ $ pm grant io.github.muntashirakon.setedit android.permission.WRITE_SETTINGS

Security exception: Permission android.permission.WRITE_SETTINGS requested by io.github.muntashirakon.setedit is not a changeable permission type

java.lang.SecurityException: Permission android.permission.WRITE_SETTINGS requested by io.github.muntashirakon.setedit is not a changeable permission type
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:448)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2282)
        at com.android.server.pm.permission.PermissionManagerService.access$1100(PermissionManagerService.java:123)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3285)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5888)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1955)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22089)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5107)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

**Comment by qmm0523** [comment]
> pm grant io.github.muntashirakon.setedit android.permission.WRITE_SECURE_SETTINGS 上边这条命令成功了，下边这个出错了。 执行命令后出错了，提示没有权限啊 d55:/ $ pm grant io.github.muntashirakon.setedit android.permission.WRITE_SETTINGS
> 
> Security exception: Permission android.permission.WRITE_SETTINGS requested by io.github.muntashirakon.setedit is not a changeable permission type
> 
> java.lang.SecurityException: Permission android.permission.WRITE_SETTINGS requested by io.github.muntashirakon.setedit is not a changeable permission type at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:448) at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2282) at com.android.server.pm.permission.PermissionManagerService.access$1100(PermissionManagerService.java:123) at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3285) at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5888) at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1955) at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230) at android.os.ShellCommand.exec(ShellCommand.java:104) at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22089) at android.os.Binder.shellCommand(Binder.java:881) at android.os.Binder.onTransact(Binder.java:765) at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5107) at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4152) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)

试一下appops set io.github.muntashirakon.setedit WRITE_SETTINGS allow
